redo:
  properties:
    project_name: "redo"
    docker_registry_namespace: "elnebuloso"

  branches:
    master:
      regex: "^main$"
      docker_push:
        - "{{ docker_tag_rolling_patch }}"
        - "{{ docker_tag_rolling_minor }}"
        - "{{ docker_tag_rolling_major }}"
        - "{{ docker_tag_latest }}"
