properties:
  project:
    type: array
    info: The Project Configuration
    properties:
      name:
        type: scalar
      folder:
        type: scalar

  docker:
    type: array
    info: The Docker Configuration
    properties:
      registry:
        type: array
        info: The Docker Registry Configuration
        properties:
          hostname:
            type: scalar
            info: Hostname of the Docker Registry
          namespace:
            type: scalar
            info: Namespace of the Docker Registry
      username:
        type: scalar
        info: Username to use for the docker login against the Docker Registry
      password:
        type: scalar
        info: Password to use for the docker login against the Docker Registry
        sensitive: true
      build:
        type: array
        info: The Docker Build Configuration
        properties:
          file:
            type: scalar
            info: Docker Filename
          context:
            type: scalar
            info: Docker Context
      push:
        type: array
        info: The Docker Tags that should be pushed into the Docker Registry
